### ISSUE TITLE
Provide a way to set fan to "auto"

### ISSUE THREAD

**Issue by sgtsquiggs** [kovapatrik/homebridge-blueair-purifier#8]
**Is your feature request related to a problem? Please describe:**
I cannot seem to set the fan to auto w/ Homebridge & Apple Home.

**Describe the solution you'd like:**
I'd love an option to disable the fan control as a slider and have it be an on-off toggle between off and auto.

If Home had the concept of a positioned switch I'd prefer that: off/auto/nightmode. I can dream.

**Describe alternatives you've considered:**
Using the BlueAir app :(

**Additional context:**

**Comment by kovapatrik** [comment]
It's a bit hidden, but you should be able to set it to auto/nightmode. For nightmode you need to adjust the configuration of the plugin. From the Homebridge UI you can do that easily, you just need to enable `Night Mode` and a switch will be created for it.

The auto fan mode is available in the main accessory: if you have multiple accessories created with the purifier (it might be the case by default, I don't really remember, sorry), you have to click on the purifier, click on `Accessories`, select the purifier again and there should be an `Auto/Manual` switch.

**Comment by kovapatrik** [comment]
Did you find the features you needed?

**Comment by kovapatrik** [comment]
Closing until further discussions.
